FROM node:10.16.2-slim as builder

RUN npm install -g yarn

RUN mkdir -p app
WORKDIR /app
COPY ./package.json .
RUN yarn
COPY . .
RUN yarn build

FROM nginx

RUN rm -rf /etc/nginx/conf.d
COPY conf /etc/nginx

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
